import { useRef, useState } from 'react'
import { useStore } from '../store'
import { rdfTextToGraph, rdfExtSupported } from '../lib/rdfImport'
import { IS_WEB, EXAMPLE_URL } from '../lib/webBuild'

export function Landing() {
  const loadGraph = useStore((s) => s.loadGraph)
  const loadError = useStore((s) => s.loadError)
  const setLoadError = useStore((s) => s.setLoadError)
  const fileInputRef = useRef(null)
  const [dragging, setDragging] = useState(false)
  const [loading, setLoading] = useState(false)

  function loadFile(file) {
    if (!file) return
    const ext = file.name.split('.').pop().toLowerCase()
    const isJson = ext === 'json'
    const isRdf = rdfExtSupported(ext)
    if (!isJson && !isRdf) {
      setLoadError('Please drop a .json file or an RDF file (.ttl, .trig, .nt, .nq, .n3). RDF/XML (.rdf) is not supported – please convert it to Turtle/TriG first.')
      return
    }
    setLoadError('')
    setLoading(true)
    const r = new FileReader()
    r.onload = (e) => {
      try {
        const text = e.target.result
        // .json = pre-built graph model; RDF = parse + convert client-side
        const data = isJson ? JSON.parse(text) : rdfTextToGraph(text, ext, file.name)
        loadGraph(data)
      } catch (err) {
        setLoadError('Error: ' + err.message)
      } finally {
        setLoading(false)
      }
    }
    r.onerror = () => {
      setLoading(false)
      setLoadError('Error reading file.')
    }
    r.readAsText(file, 'utf-8')
  }

  // Nur in der Web-Fassung: Die Beispieldaten liegen dort neben der Seite.
  // Lokal (file://, Standalone) ließe sich die Datei so gar nicht holen.
  async function loadExample() {
    setLoadError('')
    setLoading(true)
    try {
      const res = await fetch(EXAMPLE_URL)
      if (!res.ok) throw new Error('example data not found (' + res.status + ')')
      loadGraph(await res.json())
    } catch (err) {
      setLoadError('Error: ' + err.message)
    } finally {
      setLoading(false)
    }
  }

  const dropzone = (
    <div
      className={'dropzone' + (dragging ? ' drag' : '')}
      onClick={() => fileInputRef.current?.click()}
      onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
      onDragLeave={() => setDragging(false)}
      onDrop={(e) => { e.preventDefault(); setDragging(false); loadFile(e.dataTransfer.files[0]) }}
    >
      <div className="drop-ico">&#128194;</div>
      <p>Drop graph JSON or RDF here</p>
      <small>.json (OntoCartographer Studio) &middot; or RDF: .ttl, .trig, .nt, .nq, .n3</small>
      <input
        ref={fileInputRef}
        type="file"
        accept=".json,.ttl,.trig,.nt,.nq,.n3"
        style={{ display: 'none' }}
        onChange={(e) => loadFile(e.target.files[0])}
      />
    </div>
  )

  return (
    <div id="landing">
      <div className="land-box">
        <div className="land-icon">&#9906;</div>
        <h1>
          Graph<span>Explorer</span>
        </h1>
        <p className="land-sub">Explore RDF/CIDOC-CRM knowledge graphs interactively</p>
        {IS_WEB ? (
          <div className="land-choices">
            {dropzone}
            <button className="dropzone example" onClick={loadExample} disabled={loading}>
              <div className="drop-ico">&#128202;</div>
              <p>Try the example data</p>
              <small>A small fictional excavation, ready to explore</small>
            </button>
          </div>
        ) : dropzone}
        <div className="err">{loadError}</div>
        {loading && <div className="load-info">Loading&hellip;</div>}
        {IS_WEB && (
          <div className="land-privacy">
            Your files are read only in this browser tab &ndash; nothing is uploaded.
            For QGIS and Blender, use the local version.
          </div>
        )}
        <div className="land-hint">Generated by OntoCartographer Studio &rarr; Export &rarr; Explore</div>
      </div>
    </div>
  )
}
